"""
app.py
------
Main Flask application for the AI-Based Disease Prediction &
Healthcare Recommendation System.

Routes:
    /            - Home page
    /predict     - Symptom input form (GET) and prediction handler (POST)
    /result      - Displays prediction result + healthcare recommendations
    /about       - Project overview / ML workflow explanation
    /contact     - Contact page

Educational project only - not a substitute for professional medical advice.
"""

import os
import pickle
import json

import pandas as pd
from flask import Flask, render_template, request, redirect, url_for, session, flash, send_file

from utils.disease_info import get_disease_info
from utils.database import init_db, save_prediction, get_all_predictions, get_dashboard_stats
from utils.pdf_generator import generate_medical_report_pdf
from utils.auth import init_users_table, create_user, verify_user, login_required

# ---------------------------------------------------------------------
# App configuration
# ---------------------------------------------------------------------
app = Flask(__name__)
app.secret_key = "disease_prediction_secret_key_2026"  # needed for session/flash

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.path.join(BASE_DIR, "model")

# ---------------------------------------------------------------------
# Load trained model + encoders ONCE at startup (not per-request)
# ---------------------------------------------------------------------
with open(os.path.join(MODEL_DIR, "disease_model.pkl"), "rb") as f:
    model = pickle.load(f)

with open(os.path.join(MODEL_DIR, "gender_encoder.pkl"), "rb") as f:
    gender_encoder = pickle.load(f)

with open(os.path.join(MODEL_DIR, "disease_encoder.pkl"), "rb") as f:
    disease_encoder = pickle.load(f)

with open(os.path.join(MODEL_DIR, "feature_columns.pkl"), "rb") as f:
    feature_data = pickle.load(f)
    FEATURE_COLUMNS = feature_data["feature_columns"]
    SYMPTOM_COLUMNS = feature_data["symptom_columns"]

# Human-readable labels for symptoms shown in the UI,
# e.g. "excessive_thirst" -> "Excessive Thirst"
SYMPTOM_DISPLAY = {
    symptom: symptom.replace("_", " ").title() for symptom in SYMPTOM_COLUMNS
}

# Load model comparison metrics (generated by train_model.py) for the About page
with open(os.path.join(MODEL_DIR, "metrics.json"), "r") as f:
    MODEL_METRICS = json.load(f)

# Initialize the prediction history database (creates the table if missing)
init_db()

# Initialize the users table (creates it, and adds user_id to predictions if missing)
init_users_table()


# ---------------------------------------------------------------------
# Helper: compute a Low / Medium / High risk level
# ---------------------------------------------------------------------
def compute_risk_level(confidence: float, base_risk: str) -> str:
    """
    Combine the model's prediction confidence with the disease's
    baseline clinical risk to produce a final risk level.

    Logic:
    - Low confidence (<60%) means the model itself is unsure,
      so we never show a scary "High" risk on a shaky prediction.
    - Otherwise, we trust the disease's documented baseline risk.
    """
    if confidence < 60:
        return "Low"
    return base_risk


# ---------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------
@app.route("/")
def home():
    return render_template("home.html")


@app.route("/predict", methods=["GET", "POST"])
@login_required
def predict():
    if request.method == "GET":
        # Show the symptom input form
        return render_template("predict.html", symptoms=SYMPTOM_DISPLAY)

    # ---- POST: handle form submission ----
    try:
        patient_name = request.form.get("patient_name", "").strip()
        age = request.form.get("age", "").strip()
        gender = request.form.get("gender", "").strip()
        selected_symptoms = request.form.getlist("symptoms")

        # ---- Input validation ----
        if not patient_name:
            flash("Please enter the patient's name.")
            return redirect(url_for("predict"))

        if not age or not age.isdigit() or int(age) <= 0 or int(age) > 120:
            flash("Please enter a valid age between 1 and 120.")
            return redirect(url_for("predict"))

        if gender not in ("Male", "Female"):
            flash("Please select a valid gender.")
            return redirect(url_for("predict"))

        if not selected_symptoms:
            flash("Please select at least one symptom to get a prediction.")
            return redirect(url_for("predict"))

        if len(selected_symptoms) < 2:
            flash("For a more reliable prediction, please select at least 2 symptoms.")
            return redirect(url_for("predict"))

        # ---- Build feature vector in the exact column order used during training ----
        age = int(age)
        gender_encoded = gender_encoder.transform([gender])[0]

        feature_row = []
        for col in FEATURE_COLUMNS:
            if col == "Age":
                feature_row.append(age)
            elif col == "Gender":
                feature_row.append(gender_encoded)
            else:
                feature_row.append(1 if col in selected_symptoms else 0)

        # ---- Predict ----
        feature_df = pd.DataFrame([feature_row], columns=FEATURE_COLUMNS)
        prediction_encoded = model.predict(feature_df)[0]
        predicted_disease = disease_encoder.inverse_transform([prediction_encoded])[0]

        # Confidence score = probability of the predicted class
        if hasattr(model, "predict_proba"):
            probabilities = model.predict_proba(feature_df)[0]
            confidence = round(max(probabilities) * 100, 2)
        else:
            confidence = None

        # ---- Fetch disease metadata ----
        info = get_disease_info(predicted_disease)
        risk_level = compute_risk_level(confidence or 0, info["base_risk"])

        # ---- Store result in session, then redirect (Post/Redirect/Get pattern) ----
        session["result"] = {
            "patient_name": patient_name,
            "disease": predicted_disease,
            "confidence": confidence,
            "risk_level": risk_level,
            "age": age,
            "gender": gender,
            "selected_symptoms": [SYMPTOM_DISPLAY[s] for s in selected_symptoms],
            "description": info["description"],
            "causes": info["causes"],
            "precautions": info["precautions"],
            "lifestyle_tips": info["lifestyle_tips"],
            "diet": info["diet"],
            "exercise": info["exercise"],
            "when_to_consult": info["when_to_consult"],
            "specialist": info["specialist"],
        }

        # ---- Save this prediction to history (SQLite) ----
        save_prediction(
            patient_name=patient_name,
            age=age,
            gender=gender,
            symptoms=[SYMPTOM_DISPLAY[s] for s in selected_symptoms],
            disease=predicted_disease,
            confidence=confidence,
            risk_level=risk_level,
            user_id=session.get("user_id"),
        )

        return redirect(url_for("result"))

    except Exception as e:
        # Catch-all error handling so the app never crashes ungracefully
        flash(f"Something went wrong while processing your request: {e}")
        return redirect(url_for("predict"))


@app.route("/result")
def result():
    result_data = session.get("result")
    if not result_data:
        # Prevents users from visiting /result directly without a prediction
        flash("Please submit your symptoms first to view a result.")
        return redirect(url_for("predict"))

    return render_template("result.html", result=result_data)


@app.route("/download-report")
def download_report():
    """Generate and stream the PDF medical report for the current session's result."""
    result_data = session.get("result")
    if not result_data:
        flash("Please complete a prediction first to download a report.")
        return redirect(url_for("predict"))

    pdf_buffer = generate_medical_report_pdf(result_data)
    filename = f"MediPredict_Report_{result_data.get('patient_name', 'Patient').replace(' ', '_')}.pdf"

    return send_file(
        pdf_buffer,
        mimetype="application/pdf",
        as_attachment=True,
        download_name=filename,
    )


@app.route("/dashboard")
@login_required
def dashboard():
    user_id = session.get("user_id")
    stats = get_dashboard_stats(user_id=user_id)
    recent = get_all_predictions(limit=5, user_id=user_id)
    return render_template("dashboard.html", stats=stats, recent=recent)


@app.route("/history")
@login_required
def history():
    predictions = get_all_predictions(user_id=session.get("user_id"))
    return render_template("history.html", predictions=predictions)


@app.route("/about")
def about():
    return render_template("about.html", metrics=MODEL_METRICS)


@app.route("/contact")
def contact():
    return render_template("contact.html")


@app.route("/signup", methods=["GET", "POST"])
def signup():
    if session.get("user_id"):
        return redirect(url_for("home"))

    if request.method == "GET":
        return render_template("signup.html")

    username = request.form.get("username", "").strip()
    password = request.form.get("password", "")
    confirm_password = request.form.get("confirm_password", "")

    if not username or len(username) < 3:
        flash("Username must be at least 3 characters long.")
        return redirect(url_for("signup"))

    if not password or len(password) < 6:
        flash("Password must be at least 6 characters long.")
        return redirect(url_for("signup"))

    if password != confirm_password:
        flash("Passwords do not match.")
        return redirect(url_for("signup"))

    success, error = create_user(username, password)
    if not success:
        flash(error)
        return redirect(url_for("signup"))

    flash("Account created successfully! Please log in.")
    return redirect(url_for("login"))


@app.route("/login", methods=["GET", "POST"])
def login():
    if session.get("user_id"):
        return redirect(url_for("home"))

    if request.method == "GET":
        return render_template("login.html")

    username = request.form.get("username", "").strip()
    password = request.form.get("password", "")

    user = verify_user(username, password)
    if not user:
        flash("Invalid username or password.")
        return redirect(url_for("login"))

    session["user_id"] = user["id"]
    session["username"] = user["username"]

    flash(f"Welcome back, {user['username']}!")
    next_page = request.args.get("next")
    return redirect(next_page or url_for("home"))


@app.route("/logout")
def logout():
    session.clear()
    flash("You have been logged out.")
    return redirect(url_for("home"))


# ---------------------------------------------------------------------
# Error handlers
# ---------------------------------------------------------------------
@app.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
