"""
train_model.py
---------------
End-to-end ML training pipeline for the Disease Prediction System.

Workflow:
1. Load the dataset generated by dataset/generate_dataset.py
2. Preprocess: label-encode categorical columns
3. Train-test split
4. Train three models: Random Forest, Decision Tree, Logistic Regression
5. Evaluate each on Accuracy, Precision, Recall, F1 Score
6. Save a Confusion Matrix plot + full Classification Report for the best model
7. Automatically select the best-performing model (by test accuracy)
8. Persist the winning model + encoders + feature/metrics info using pickle,
   ready for app.py to load at request time.
"""

import os
import json
import pickle

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")  # no display backend needed, we only save images
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
)

# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_PATH = os.path.join(BASE_DIR, "dataset", "disease_symptom_dataset.csv")
MODEL_DIR = os.path.join(BASE_DIR, "model")
os.makedirs(MODEL_DIR, exist_ok=True)

# ---------------------------------------------------------------------
# 1. Load dataset
# ---------------------------------------------------------------------
print("Loading dataset...")
df = pd.read_csv(DATASET_PATH)
print(f"Dataset shape: {df.shape}")

# ---------------------------------------------------------------------
# 2. Preprocessing
# ---------------------------------------------------------------------
print("\nPreprocessing data...")

# Encode Gender (Male/Female -> 0/1)
gender_encoder = LabelEncoder()
df["Gender"] = gender_encoder.fit_transform(df["Gender"])

# Encode Disease (target label -> integers)
disease_encoder = LabelEncoder()
df["Disease"] = disease_encoder.fit_transform(df["Disease"])

# Feature columns = everything except Disease
feature_columns = [col for col in df.columns if col != "Disease"]
symptom_columns = [col for col in feature_columns if col not in ("Age", "Gender")]

X = df[feature_columns]
y = df["Disease"]

print(f"Number of features: {len(feature_columns)} (Age, Gender + {len(symptom_columns)} symptoms)")
print(f"Number of disease classes: {len(disease_encoder.classes_)}")

# ---------------------------------------------------------------------
# 3. Train-test split (stratified to keep class balance in both sets)
# ---------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"\nTrain size: {X_train.shape[0]}, Test size: {X_test.shape[0]}")

# ---------------------------------------------------------------------
# 4. Train and evaluate multiple models
# ---------------------------------------------------------------------
models = {
    "Random Forest": RandomForestClassifier(n_estimators=150, max_depth=25, random_state=42, n_jobs=1),
    "Decision Tree": DecisionTreeClassifier(max_depth=25, random_state=42),
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
}

results = {}
trained_models = {}

print("\n" + "=" * 60)
print("MODEL TRAINING & EVALUATION")
print("=" * 60)

for name, model in models.items():
    model.fit(X_train, y_train)

    train_preds = model.predict(X_train)
    test_preds = model.predict(X_test)

    train_acc = accuracy_score(y_train, train_preds)
    test_acc = accuracy_score(y_test, test_preds)
    precision = precision_score(y_test, test_preds, average="weighted", zero_division=0)
    recall = recall_score(y_test, test_preds, average="weighted", zero_division=0)
    f1 = f1_score(y_test, test_preds, average="weighted", zero_division=0)

    results[name] = {
        "train_accuracy": round(train_acc, 4),
        "test_accuracy": round(test_acc, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1_score": round(f1, 4),
    }
    trained_models[name] = model

    print(f"\n{name}")
    print(f"  Training Accuracy : {train_acc:.4f}")
    print(f"  Testing  Accuracy : {test_acc:.4f}")
    print(f"  Precision (weighted): {precision:.4f}")
    print(f"  Recall (weighted)   : {recall:.4f}")
    print(f"  F1 Score (weighted) : {f1:.4f}")

# ---------------------------------------------------------------------
# 5. Automatically select the best model (highest test accuracy)
# ---------------------------------------------------------------------
best_model_name = max(results, key=lambda name: results[name]["test_accuracy"])
best_model = trained_models[best_model_name]

print("\n" + "=" * 60)
print(f"BEST MODEL SELECTED: {best_model_name}")
print(f"Test Accuracy: {results[best_model_name]['test_accuracy']}")
print("=" * 60)

# ---------------------------------------------------------------------
# 6. Detailed evaluation of the best model
# ---------------------------------------------------------------------
best_preds = best_model.predict(X_test)

# Classification report (per-class precision/recall/f1)
class_report = classification_report(
    y_test, best_preds, target_names=disease_encoder.classes_, zero_division=0
)
print("\nClassification Report (Best Model):\n")
print(class_report)

with open(os.path.join(MODEL_DIR, "classification_report.txt"), "w") as f:
    f.write(f"Best Model: {best_model_name}\n\n")
    f.write(class_report)

# Confusion matrix plot
# NOTE: with a large number of classes, per-cell annotations and full tick
# labels become both illegible and extremely heavy to render, so we scale
# the plot's detail level down as the class count grows.
cm = confusion_matrix(y_test, best_preds)
num_classes = len(disease_encoder.classes_)

if num_classes <= 30:
    plt.figure(figsize=(14, 12))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues",
        xticklabels=disease_encoder.classes_,
        yticklabels=disease_encoder.classes_,
    )
    plt.xticks(rotation=90)
    plt.yticks(rotation=0)
else:
    # Too many classes for readable per-cell numbers or tick labels -
    # render just the heatmap pattern (still useful to show diagonal
    # dominance / where confusion clusters), without labels or annotations.
    plt.figure(figsize=(10, 9))
    sns.heatmap(cm, annot=False, cmap="Blues", xticklabels=False, yticklabels=False)

plt.title(f"Confusion Matrix - {best_model_name} ({num_classes} classes)")
plt.xlabel("Predicted Disease")
plt.ylabel("Actual Disease")
plt.tight_layout()
cm_path = os.path.join(BASE_DIR, "static", "img", "confusion_matrix.png")
plt.savefig(cm_path, dpi=120)
plt.close()
print(f"\nConfusion matrix saved to: {cm_path}")

# ---------------------------------------------------------------------
# 7. Save best model + encoders + metadata using pickle
# ---------------------------------------------------------------------
with open(os.path.join(MODEL_DIR, "disease_model.pkl"), "wb") as f:
    pickle.dump(best_model, f)

with open(os.path.join(MODEL_DIR, "gender_encoder.pkl"), "wb") as f:
    pickle.dump(gender_encoder, f)

with open(os.path.join(MODEL_DIR, "disease_encoder.pkl"), "wb") as f:
    pickle.dump(disease_encoder, f)

with open(os.path.join(MODEL_DIR, "feature_columns.pkl"), "wb") as f:
    pickle.dump({"feature_columns": feature_columns, "symptom_columns": symptom_columns}, f)

# Save all model comparison results + which one was chosen, as JSON
# (app.py / About page can display this for transparency)
metrics_summary = {
    "results": results,
    "best_model": best_model_name,
    "num_diseases": len(disease_encoder.classes_),
    "num_symptoms": len(symptom_columns),
    "train_size": int(X_train.shape[0]),
    "test_size": int(X_test.shape[0]),
}
with open(os.path.join(MODEL_DIR, "metrics.json"), "w") as f:
    json.dump(metrics_summary, f, indent=2)

print("\nAll model artifacts saved to /model:")
print("  - disease_model.pkl       (trained best model)")
print("  - gender_encoder.pkl      (LabelEncoder for Gender)")
print("  - disease_encoder.pkl     (LabelEncoder for Disease labels)")
print("  - feature_columns.pkl     (ordered feature/symptom column names)")
print("  - metrics.json            (model comparison results)")
print("  - classification_report.txt")
print("\nTraining complete.")
